Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: ../organizations/ordererOrganizations/auto.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
    OrdererEndpoints:
      - orderer.auto.com:7050
  - &Farmers
    Name: FarmersMSP
    ID: FarmersMSP
    MSPDir: ../organizations/peerOrganizations/farmers.auto.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('FarmersMSP.admin', 'FarmersMSP.peer', 'FarmersMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('FarmersMSP.admin', 'FarmersMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('FarmersMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('FarmersMSP.peer')"
  - &Processors
    Name: ProcessorsMSP
    ID: ProcessorsMSP
    MSPDir: ../organizations/peerOrganizations/processors.auto.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ProcessorsMSP.admin', 'ProcessorsMSP.peer', 'ProcessorsMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('ProcessorsMSP.admin', 'ProcessorsMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('ProcessorsMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('ProcessorsMSP.peer')"

  - &Distributors
    Name: DistributorsMSP
    ID: DistributorsMSP
    MSPDir: ../organizations/peerOrganizations/distributors.auto.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('DistributorsMSP.admin', 'DistributorsMSP.peer', 'DistributorsMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('DistributorsMSP.admin', 'DistributorsMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('DistributorsMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('DistributorsMSP.peer')"

Capabilities:  
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_5: true
    
Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  Addresses:
    - orderer.auto.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  ThreeOrgsChannel:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      OrdererType: etcdraft
      EtcdRaft:
        Consenters:
          - Host: orderer.auto.com
            Port: 7050
            ClientTLSCert: ../organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls/server.crt
            ServerTLSCert: ../organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls/server.crt
      Organizations:
        - *OrdererOrg
      Capabilities: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Farmers
        - *Processors
        - *Distributors
      Capabilities: *ApplicationCapabilities