#!/bin/bash

function createFarmers() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/farmers.auto.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/farmers.auto.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-farmers --tls.certfiles "${PWD}/organizations/fabric-ca/farmers/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-farmers.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-farmers.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-farmers.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-farmers.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/farmers.auto.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy farmers's CA cert to farmers's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/farmers.auto.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/farmers/ca-cert.pem" "${PWD}/organizations/peerOrganizations/farmers.auto.com/msp/tlscacerts/ca.crt"

  # Copy farmers's CA cert to farmers's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/farmers.auto.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/farmers/ca-cert.pem" "${PWD}/organizations/peerOrganizations/farmers.auto.com/tlsca/tlsca.farmers.auto.com-cert.pem"

  # Copy farmers's CA cert to farmers's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/farmers.auto.com/ca"
  cp "${PWD}/organizations/fabric-ca/farmers/ca-cert.pem" "${PWD}/organizations/peerOrganizations/farmers.auto.com/ca/ca.farmers.auto.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-farmers --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/farmers/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-farmers --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/farmers/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-farmers --id.name farmersadmin --id.secret farmersadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/farmers/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-farmers -M "${PWD}/organizations/peerOrganizations/farmers.auto.com/peers/peer0.farmers.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/farmers/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/farmers.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/farmers.auto.com/peers/peer0.farmers.auto.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-farmers -M "${PWD}/organizations/peerOrganizations/farmers.auto.com/peers/peer0.farmers.auto.com/tls" --enrollment.profile tls --csr.hosts peer0.farmers.auto.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/farmers/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/farmers.auto.com/peers/peer0.farmers.auto.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/farmers.auto.com/peers/peer0.farmers.auto.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/farmers.auto.com/peers/peer0.farmers.auto.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/farmers.auto.com/peers/peer0.farmers.auto.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/farmers.auto.com/peers/peer0.farmers.auto.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/farmers.auto.com/peers/peer0.farmers.auto.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-farmers -M "${PWD}/organizations/peerOrganizations/farmers.auto.com/users/User1@farmers.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/farmers/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/farmers.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/farmers.auto.com/users/User1@farmers.auto.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://farmersadmin:farmersadminpw@localhost:7054 --caname ca-farmers -M "${PWD}/organizations/peerOrganizations/farmers.auto.com/users/Admin@farmers.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/farmers/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/farmers.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/farmers.auto.com/users/Admin@farmers.auto.com/msp/config.yaml"
}

function createProcessors() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/processors.auto.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/processors.auto.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-processors --tls.certfiles "${PWD}/organizations/fabric-ca/processors/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-processors.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-processors.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-processors.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-processors.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/processors.auto.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy processors's CA cert to processors's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/processors.auto.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/processors/ca-cert.pem" "${PWD}/organizations/peerOrganizations/processors.auto.com/msp/tlscacerts/ca.crt"

  # Copy processors's CA cert to processors's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/processors.auto.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/processors/ca-cert.pem" "${PWD}/organizations/peerOrganizations/processors.auto.com/tlsca/tlsca.processors.auto.com-cert.pem"

  # Copy processors's CA cert to processors's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/processors.auto.com/ca"
  cp "${PWD}/organizations/fabric-ca/processors/ca-cert.pem" "${PWD}/organizations/peerOrganizations/processors.auto.com/ca/ca.processors.auto.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-processors --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/processors/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-processors --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/processors/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-processors --id.name processorsadmin --id.secret processorsadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/processors/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-processors -M "${PWD}/organizations/peerOrganizations/processors.auto.com/peers/peer0.processors.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/processors/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/processors.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/processors.auto.com/peers/peer0.processors.auto.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-processors -M "${PWD}/organizations/peerOrganizations/processors.auto.com/peers/peer0.processors.auto.com/tls" --enrollment.profile tls --csr.hosts peer0.processors.auto.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/processors/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/processors.auto.com/peers/peer0.processors.auto.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/processors.auto.com/peers/peer0.processors.auto.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/processors.auto.com/peers/peer0.processors.auto.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/processors.auto.com/peers/peer0.processors.auto.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/processors.auto.com/peers/peer0.processors.auto.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/processors.auto.com/peers/peer0.processors.auto.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-processors -M "${PWD}/organizations/peerOrganizations/processors.auto.com/users/User1@processors.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/processors/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/processors.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/processors.auto.com/users/User1@processors.auto.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://processorsadmin:processorsadminpw@localhost:8054 --caname ca-processors -M "${PWD}/organizations/peerOrganizations/processors.auto.com/users/Admin@processors.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/processors/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/processors.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/processors.auto.com/users/Admin@processors.auto.com/msp/config.yaml"
}


function createDistributors() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/distributors.auto.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/distributors.auto.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname ca-distributors --tls.certfiles "${PWD}/organizations/fabric-ca/distributors/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-distributors.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-distributors.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-distributors.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-distributors.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/distributors.auto.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy distributors's CA cert to distributors's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/distributors.auto.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/distributors/ca-cert.pem" "${PWD}/organizations/peerOrganizations/distributors.auto.com/msp/tlscacerts/ca.crt"

  # Copy distributors's CA cert to distributors's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/distributors.auto.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/distributors/ca-cert.pem" "${PWD}/organizations/peerOrganizations/distributors.auto.com/tlsca/tlsca.distributors.auto.com-cert.pem"

  # Copy distributors's CA cert to distributors's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/distributors.auto.com/ca"
  cp "${PWD}/organizations/fabric-ca/distributors/ca-cert.pem" "${PWD}/organizations/peerOrganizations/distributors.auto.com/ca/ca.distributors.auto.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-distributors --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/distributors/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-distributors --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/distributors/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-distributors --id.name distributorsadmin --id.secret distributorsadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/distributors/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-distributors -M "${PWD}/organizations/peerOrganizations/distributors.auto.com/peers/peer0.distributors.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/distributors/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/distributors.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/distributors.auto.com/peers/peer0.distributors.auto.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-distributors -M "${PWD}/organizations/peerOrganizations/distributors.auto.com/peers/peer0.distributors.auto.com/tls" --enrollment.profile tls --csr.hosts peer0.distributors.auto.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/distributors/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/distributors.auto.com/peers/peer0.distributors.auto.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/distributors.auto.com/peers/peer0.distributors.auto.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/distributors.auto.com/peers/peer0.distributors.auto.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/distributors.auto.com/peers/peer0.distributors.auto.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/distributors.auto.com/peers/peer0.distributors.auto.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/distributors.auto.com/peers/peer0.distributors.auto.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:11054 --caname ca-distributors -M "${PWD}/organizations/peerOrganizations/distributors.auto.com/users/User1@distributors.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/distributors/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/distributors.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/distributors.auto.com/users/User1@distributors.auto.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://distributorsadmin:distributorsadminpw@localhost:11054 --caname ca-distributors -M "${PWD}/organizations/peerOrganizations/distributors.auto.com/users/Admin@distributors.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/distributors/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/distributors.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/distributors.auto.com/users/Admin@distributors.auto.com/msp/config.yaml"
}


function createOrderer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/auto.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/auto.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/auto.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/auto.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/auto.com/msp/tlscacerts/tlsca.auto.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/auto.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/auto.com/tlsca/tlsca.auto.com-cert.pem"

  echo "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/auto.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/msp/config.yaml"

  echo "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls" --enrollment.profile tls --csr.hosts orderer.auto.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/msp/tlscacerts/tlsca.auto.com-cert.pem"

  echo "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/auto.com/users/Admin@auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/auto.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/auto.com/users/Admin@auto.com/msp/config.yaml"
}

createFarmers
createProcessors
createDistributors
createOrderer